<div class="col-md-6">
    <div class="input-group phone">
        <span class="input-group-addon">
            <select data-live-search="true" id="phone_prefix" name="prefix"
                    class="form-control selectpicker"
                    style="width: auto; display: inline-block;">
                 <option label="+1" value="+1"></option>
                <option label="+1-473" value="+1-473"></option>
                <option label="+1-758" value="+1-758"></option>
                <option label="+1-767" value="+1-767"></option>
                <option label="+1-784" value="+1-784"></option>
                <option label="+1-809" value="+1-809"></option>
                <option label="+1-868" value="+1-868"></option>
                <option label="+1-869" value="+1-869"></option>
                <option label="+1-876" value="+1-876"></option>
                <option label="+20" value="+20"></option>
                <option label="+211" value="+211"></option>
                <option label="+212" value="+212"></option>
                <option label="+213" value="+213"></option>
                <option label="+216" value="+216"></option>
                <option label="+218" value="+218"></option>
                <option label="+220" value="+220"></option>
                <option label="+221" value="+221"></option>
                <option label="+222" value="+222"></option>
                <option label="+223" value="+223"></option>
                <option label="+224" value="+224"></option>
                <option label="+226" value="+226"></option>
                <option label="+227" value="+227"></option>
                <option label="+228" value="+228"></option>
                <option label="+229" value="+229"></option>
                <option label="+230" value="+230"></option>
                <option label="+231" value="+231"></option>
                <option label="+232" value="+232"></option>
                <option label="+233" value="+233"></option>
                <option label="+234" value="+234"></option>
                <option label="+235" value="+235"></option>
                <option label="+236" value="+236"></option>
                <option label="+237" value="+237"></option>
                <option label="+238" value="+238"></option>
                <option label="+239" value="+239"></option>
                <option label="+240" value="+240"></option>
                <option label="+241" value="+241"></option>
                <option label="+242" value="+242"></option>
                <option label="+243" value="+243"></option>
                <option label="+244" value="+244"></option>
                <option label="+245" value="+245"></option>
                <option label="+248" value="+248"></option>
                <option label="+249" value="+249"></option>
                <option label="+250" value="+250"></option>
                <option label="+251" value="+251"></option>
                <option label="+252" value="+252"></option>
                <option label="+253" value="+253"></option>
                <option label="+254" value="+254"></option>
                <option label="+255" value="+255"></option>
                <option label="+256" value="+256"></option>
                <option label="+257" value="+257"></option>
                <option label="+258" value="+258"></option>
                <option label="+260" value="+260"></option>
                <option label="+261" value="+261"></option>
                <option label="+263" value="+263"></option>
                <option label="+264" value="+264"></option>
                <option label="+265" value="+265"></option>
                <option label="+266" value="+266"></option>
                <option label="+267" value="+267"></option>
                <option label="+268" value="+268"></option>
                <option label="+269" value="+269"></option>
                <option label="+27" value="+27"></option>
                <option label="+291" value="+291"></option>
                <option label="+30" value="+30"></option>
                <option label="+31" value="+31"></option>
                <option label="+32" value="+32"></option>
                <option label="+33" value="+33"></option>
                <option label="+34" value="+34"></option>
                <option label="+351" value="+351"></option>
                <option label="+352" value="+352"></option>
                <option label="+353" value="+353"></option>
                <option label="+354" value="+354"></option>
                <option label="+355" value="+355"></option>
                <option label="+356" value="+356"></option>
                <option label="+357" value="+357"></option>
                <option label="+358" value="+358"></option>
                <option label="+359" value="+359"></option>
                <option label="+36" value="+36"></option>
                <option label="+370" value="+370"></option>
                <option label="+371" value="+371"></option>
                <option label="+372" value="+372"></option>
                <option label="+373" value="+373"></option>
                <option label="+374" value="+374"></option>
                <option label="+375" value="+375"></option>
                <option label="+376" value="+376"></option>
                <option label="+377" value="+377"></option>
                <option label="+378" value="+378"></option>
                <option label="+379" value="+379"></option>
                <option label="+380" value="+380"></option>
                <option label="+381" value="+381"></option>
                <option label="+382" value="+382"></option>
                <option label="+385" value="+385"></option>
                <option label="+386" value="+386"></option>
                <option label="+387" value="+387"></option>
                <option label="+389" value="+389"></option>
                <option label="+39" value="+39"></option>
                <option label="+40" value="+40"></option>
                <option label="+41" value="+41"></option>
                <option label="+420" value="+420"></option>
                <option label="+421" value="+421"></option>
                <option label="+423" value="+423"></option>
                <option label="+43" value="+43"></option>
                <option label="+44" value="+44"></option>
                <option label="+45" value="+45"></option>
                <option label="+46" value="+46"></option>
                <option label="+47" value="+47"></option>
                <option label="+48" value="+48"></option>
                <option label="+49" value="+49"></option>
                <option label="+501" value="+501"></option>
                <option label="+502" value="+502"></option>
                <option label="+503" value="+503"></option>
                <option label="+504" value="+504"></option>
                <option label="+505" value="+505"></option>
                <option label="+506" value="+506"></option>
                <option label="+507" value="+507"></option>
                <option label="+509" value="+509"></option>
                <option label="+51" value="+51"></option>
                <option label="+52" value="+52"></option>
                <option label="+53" value="+53"></option>
                <option label="+54" value="+54"></option>
                <option label="+55" value="+55"></option>
                <option label="+56" value="+56"></option>
                <option label="+57" value="+57"></option>
                <option label="+58" value="+58"></option>
                <option label="+591" value="+591"></option>
                <option label="+592" value="+592"></option>
                <option label="+593" value="+593"></option>
                <option label="+595" value="+595"></option>
                <option label="+597" value="+597"></option>
                <option label="+598" value="+598"></option>
                <option label="+60" value="+60"></option>
                <option label="+61" value="+61"></option>
                <option label="+62" value="+62"></option>
                <option label="+63" value="+63"></option>
                <option label="+64" value="+64"></option>
                <option label="+65" value="+65"></option>
                <option label="+66" value="+66"></option>
                <option label="+670" value="+670"></option>
                <option label="+673" value="+673"></option>
                <option label="+674" value="+674"></option>
                <option label="+675" value="+675"></option>
                <option label="+676" value="+676"></option>
                <option label="+677" value="+677"></option>
                <option label="+678" value="+678"></option>
                <option label="+679" value="+679"></option>
                <option label="+680" value="+680"></option>
                <option label="+685" value="+685"></option>
                <option label="+686" value="+686"></option>
                <option label="+688" value="+688"></option>
                <option label="+691" value="+691"></option>
                <option label="+692" value="+692"></option>
                <option label="+7" value="+7"></option>
                <option label="+81" value="+81"></option>
                <option label="+82" value="+82"></option>
                <option label="+84" value="+84"></option>
                <option label="+855" value="+855"></option>
                <option label="+856" value="+856"></option>
                <option label="+86" value="+86"></option>
                <option label="+880" value="+880"></option>
                <option label="+886" value="+886"></option>
                <option label="+90" value="+90"></option>
                <option label="+91" value="+91"></option>
                <option label="+92" value="+92"></option>
                <option label="+93" value="+93"></option>
                <option label="+94" value="+94"></option>
                <option label="+95" value="+95"></option>
                <option label="+960" value="+960"></option>
                <option label="+961" value="+961"></option>
                <option label="+962" value="+962"></option>
                <option label="+963" value="+963"></option>
                <option label="+964" value="+964"></option>
                <option label="+965" value="+965"></option>
                <option label="+966" value="+966"></option>
                <option label="+967" value="+967"></option>
                <option label="+968" value="+968"></option>
                <option label="+971" value="+971"></option>
                <option label="+972" value="+972"></option>
                <option label="+973" value="+973"></option>
                <option label="+974" value="+974"></option>
                <option label="+975" value="+975"></option>
                <option label="+976" value="+976"></option>
                <option label="+977" value="+977"></option>
                <option label="+98" value="+98"></option>
                <option label="+992" value="+992"></option>
                <option label="+993" value="+993"></option>
                <option label="+994" value="+994"></option>
                <option label="+995" value="+995"></option>
                <option label="+996" value="+996"></option>
                <option label="+998" value="+998"></option>
            </select>
        </span>
        <input type="text" class="form-control" id="phone" name="phone" placeholder="Phone">
    </div>
</div>
