<div class="form-group phone login-phone">
    <div class="col-md-6">
        <el-input placeholder="Phone" value="{{ old('phone') ?? '' }}" name="phone" class="input-with-select">
            <el-select name="prefix" value="{{ old('prefix') ?? '' }}" slot="prepend" filterable
                       placeholder="+995">
                <el-option label="+1" value="+1"></el-option>
                <el-option label="+1-473" value="+1-473"></el-option>
                <el-option label="+1-758" value="+1-758"></el-option>
                <el-option label="+1-767" value="+1-767"></el-option>
                <el-option label="+1-784" value="+1-784"></el-option>
                <el-option label="+1-809" value="+1-809"></el-option>
                <el-option label="+1-868" value="+1-868"></el-option>
                <el-option label="+1-869" value="+1-869"></el-option>
                <el-option label="+1-876" value="+1-876"></el-option>
                <el-option label="+20" value="+20"></el-option>
                <el-option label="+211" value="+211"></el-option>
                <el-option label="+212" value="+212"></el-option>
                <el-option label="+213" value="+213"></el-option>
                <el-option label="+216" value="+216"></el-option>
                <el-option label="+218" value="+218"></el-option>
                <el-option label="+220" value="+220"></el-option>
                <el-option label="+221" value="+221"></el-option>
                <el-option label="+222" value="+222"></el-option>
                <el-option label="+223" value="+223"></el-option>
                <el-option label="+224" value="+224"></el-option>
                <el-option label="+226" value="+226"></el-option>
                <el-option label="+227" value="+227"></el-option>
                <el-option label="+228" value="+228"></el-option>
                <el-option label="+229" value="+229"></el-option>
                <el-option label="+230" value="+230"></el-option>
                <el-option label="+231" value="+231"></el-option>
                <el-option label="+232" value="+232"></el-option>
                <el-option label="+233" value="+233"></el-option>
                <el-option label="+234" value="+234"></el-option>
                <el-option label="+235" value="+235"></el-option>
                <el-option label="+236" value="+236"></el-option>
                <el-option label="+237" value="+237"></el-option>
                <el-option label="+238" value="+238"></el-option>
                <el-option label="+239" value="+239"></el-option>
                <el-option label="+240" value="+240"></el-option>
                <el-option label="+241" value="+241"></el-option>
                <el-option label="+242" value="+242"></el-option>
                <el-option label="+243" value="+243"></el-option>
                <el-option label="+244" value="+244"></el-option>
                <el-option label="+245" value="+245"></el-option>
                <el-option label="+248" value="+248"></el-option>
                <el-option label="+249" value="+249"></el-option>
                <el-option label="+250" value="+250"></el-option>
                <el-option label="+251" value="+251"></el-option>
                <el-option label="+252" value="+252"></el-option>
                <el-option label="+253" value="+253"></el-option>
                <el-option label="+254" value="+254"></el-option>
                <el-option label="+255" value="+255"></el-option>
                <el-option label="+256" value="+256"></el-option>
                <el-option label="+257" value="+257"></el-option>
                <el-option label="+258" value="+258"></el-option>
                <el-option label="+260" value="+260"></el-option>
                <el-option label="+261" value="+261"></el-option>
                <el-option label="+263" value="+263"></el-option>
                <el-option label="+264" value="+264"></el-option>
                <el-option label="+265" value="+265"></el-option>
                <el-option label="+266" value="+266"></el-option>
                <el-option label="+267" value="+267"></el-option>
                <el-option label="+268" value="+268"></el-option>
                <el-option label="+269" value="+269"></el-option>
                <el-option label="+27" value="+27"></el-option>
                <el-option label="+291" value="+291"></el-option>
                <el-option label="+30" value="+30"></el-option>
                <el-option label="+31" value="+31"></el-option>
                <el-option label="+32" value="+32"></el-option>
                <el-option label="+33" value="+33"></el-option>
                <el-option label="+34" value="+34"></el-option>
                <el-option label="+351" value="+351"></el-option>
                <el-option label="+352" value="+352"></el-option>
                <el-option label="+353" value="+353"></el-option>
                <el-option label="+354" value="+354"></el-option>
                <el-option label="+355" value="+355"></el-option>
                <el-option label="+356" value="+356"></el-option>
                <el-option label="+357" value="+357"></el-option>
                <el-option label="+358" value="+358"></el-option>
                <el-option label="+359" value="+359"></el-option>
                <el-option label="+36" value="+36"></el-option>
                <el-option label="+370" value="+370"></el-option>
                <el-option label="+371" value="+371"></el-option>
                <el-option label="+372" value="+372"></el-option>
                <el-option label="+373" value="+373"></el-option>
                <el-option label="+374" value="+374"></el-option>
                <el-option label="+375" value="+375"></el-option>
                <el-option label="+376" value="+376"></el-option>
                <el-option label="+377" value="+377"></el-option>
                <el-option label="+378" value="+378"></el-option>
                <el-option label="+379" value="+379"></el-option>
                <el-option label="+380" value="+380"></el-option>
                <el-option label="+381" value="+381"></el-option>
                <el-option label="+382" value="+382"></el-option>
                <el-option label="+385" value="+385"></el-option>
                <el-option label="+386" value="+386"></el-option>
                <el-option label="+387" value="+387"></el-option>
                <el-option label="+389" value="+389"></el-option>
                <el-option label="+39" value="+39"></el-option>
                <el-option label="+40" value="+40"></el-option>
                <el-option label="+41" value="+41"></el-option>
                <el-option label="+420" value="+420"></el-option>
                <el-option label="+421" value="+421"></el-option>
                <el-option label="+423" value="+423"></el-option>
                <el-option label="+43" value="+43"></el-option>
                <el-option label="+44" value="+44"></el-option>
                <el-option label="+45" value="+45"></el-option>
                <el-option label="+46" value="+46"></el-option>
                <el-option label="+47" value="+47"></el-option>
                <el-option label="+48" value="+48"></el-option>
                <el-option label="+49" value="+49"></el-option>
                <el-option label="+501" value="+501"></el-option>
                <el-option label="+502" value="+502"></el-option>
                <el-option label="+503" value="+503"></el-option>
                <el-option label="+504" value="+504"></el-option>
                <el-option label="+505" value="+505"></el-option>
                <el-option label="+506" value="+506"></el-option>
                <el-option label="+507" value="+507"></el-option>
                <el-option label="+509" value="+509"></el-option>
                <el-option label="+51" value="+51"></el-option>
                <el-option label="+52" value="+52"></el-option>
                <el-option label="+53" value="+53"></el-option>
                <el-option label="+54" value="+54"></el-option>
                <el-option label="+55" value="+55"></el-option>
                <el-option label="+56" value="+56"></el-option>
                <el-option label="+57" value="+57"></el-option>
                <el-option label="+58" value="+58"></el-option>
                <el-option label="+591" value="+591"></el-option>
                <el-option label="+592" value="+592"></el-option>
                <el-option label="+593" value="+593"></el-option>
                <el-option label="+595" value="+595"></el-option>
                <el-option label="+597" value="+597"></el-option>
                <el-option label="+598" value="+598"></el-option>
                <el-option label="+60" value="+60"></el-option>
                <el-option label="+61" value="+61"></el-option>
                <el-option label="+62" value="+62"></el-option>
                <el-option label="+63" value="+63"></el-option>
                <el-option label="+64" value="+64"></el-option>
                <el-option label="+65" value="+65"></el-option>
                <el-option label="+66" value="+66"></el-option>
                <el-option label="+670" value="+670"></el-option>
                <el-option label="+673" value="+673"></el-option>
                <el-option label="+674" value="+674"></el-option>
                <el-option label="+675" value="+675"></el-option>
                <el-option label="+676" value="+676"></el-option>
                <el-option label="+677" value="+677"></el-option>
                <el-option label="+678" value="+678"></el-option>
                <el-option label="+679" value="+679"></el-option>
                <el-option label="+680" value="+680"></el-option>
                <el-option label="+685" value="+685"></el-option>
                <el-option label="+686" value="+686"></el-option>
                <el-option label="+688" value="+688"></el-option>
                <el-option label="+691" value="+691"></el-option>
                <el-option label="+692" value="+692"></el-option>
                <el-option label="+7" value="+7"></el-option>
                <el-option label="+81" value="+81"></el-option>
                <el-option label="+82" value="+82"></el-option>
                <el-option label="+84" value="+84"></el-option>
                <el-option label="+855" value="+855"></el-option>
                <el-option label="+856" value="+856"></el-option>
                <el-option label="+86" value="+86"></el-option>
                <el-option label="+880" value="+880"></el-option>
                <el-option label="+886" value="+886"></el-option>
                <el-option label="+90" value="+90"></el-option>
                <el-option label="+91" value="+91"></el-option>
                <el-option label="+92" value="+92"></el-option>
                <el-option label="+93" value="+93"></el-option>
                <el-option label="+94" value="+94"></el-option>
                <el-option label="+95" value="+95"></el-option>
                <el-option label="+960" value="+960"></el-option>
                <el-option label="+961" value="+961"></el-option>
                <el-option label="+962" value="+962"></el-option>
                <el-option label="+963" value="+963"></el-option>
                <el-option label="+964" value="+964"></el-option>
                <el-option label="+965" value="+965"></el-option>
                <el-option label="+966" value="+966"></el-option>
                <el-option label="+967" value="+967"></el-option>
                <el-option label="+968" value="+968"></el-option>
                <el-option label="+971" value="+971"></el-option>
                <el-option label="+972" value="+972"></el-option>
                <el-option label="+973" value="+973"></el-option>
                <el-option label="+974" value="+974"></el-option>
                <el-option label="+975" value="+975"></el-option>
                <el-option label="+976" value="+976"></el-option>
                <el-option label="+977" value="+977"></el-option>
                <el-option label="+98" value="+98"></el-option>
                <el-option label="+992" value="+992"></el-option>
                <el-option label="+993" value="+993"></el-option>
                <el-option label="+994" value="+994"></el-option>
                <el-option label="+995" value="+995"></el-option>
                <el-option label="+996" value="+996"></el-option>
                <el-option label="+998" value="+998"></el-option>
            </el-select>
        </el-input>
    </div>
</div>

